const holidays2023 = [
  {
    id: 1,
    name: "Neujahr",
    date: new Date("2023-01-01"),
    tag: "public",
  },
  {
    id: 2,
    name: "Heilige Drei Könige",
    date: new Date("2023-01-06"),
    tag: "public",
  },
  {
    id: 3,
    name: "Fasching",
    date: new Date("2023-02-28"),
    tag: "regional",
  },
  {
    id: 4,
    name: "Karfreitag",
    date: new Date("2023-04-07"),
    tag: "public",
  },
  {
    id: 5,
    name: "Ostermontag",
    date: new Date("2023-04-10"),
    tag: "public",
  },
  {
    id: 6,
    name: "Tag der Arbeit",
    date: new Date("2023-05-01"),
    tag: "public",
  },
  {
    id: 7,
    name: "Christi Himmelfahrt",
    date: new Date("2023-05-25"),
    tag: "public",
  },
  {
    id: 8,
    name: "Pfingstmontag",
    date: new Date("2023-06-05"),
    tag: "public",
  },
  {
    id: 9,
    name: "Fronleichnam",
    date: new Date("2023-06-15"),
    tag: "public",
  },
  {
    id: 10,
    name: "Mariä Himmelfahrt",
    date: new Date("2023-08-15"),
    tag: "regional",
  },
  {
    id: 11,
    name: "Tag der Deutschen Einheit",
    date: new Date("2023-10-03"),
    tag: "public",
  },
  {
    id: 12,
    name: "Reformationstag",
    date: new Date("2023-10-31"),
    tag: "public",
  },
  {
    id: 13,
    name: "Allerheiligen",
    date: new Date("2023-11-01"),
    tag: "public",
  },
  {
    id: 14,
    name: "Buß- und Bettag",
    date: new Date("2023-11-22"),
    tag: "public",
  },
  {
    id: 15,
    name: "Erster Weihnachtstag",
    date: new Date("2023-12-25"),
    tag: "public",
  },
  {
    id: 16,
    name: "Zweiter Weihnachtstag",
    date: new Date("2023-12-26"),
    tag: "public",
  },
  {
    id: 17,
    name: "Silvester",
    date: new Date("2023-12-31"),
    tag: "public",
  },
  // Bavaria regional holidays
  {
    id: 18,
    name: "Heilige Drei Könige (Bavaria)",
    date: new Date("2023-01-06"),
    tag: "regional",
  },
  {
    id: 19,
    name: "Fronleichnam (Bavaria)",
    date: new Date("2023-06-15"),
    tag: "regional",
  },
  {
    id: 20,
    name: "Mariä Himmelfahrt (Bavaria)",
    date: new Date("2023-08-15"),
    tag: "regional",
  },
];
