const dailyGifts = [
  {
    id: 1,
    name: "Candle Set",
    description: "A set of scented candles in various fragrances.",
    price: 20,
    tag: "home_decor",
  },
  {
    id: 2,
    name: "Coffee Mug",
    description: "A ceramic coffee mug with a unique design.",
    price: 10,
    tag: "kitchen",
  },
  {
    id: 3,
    name: "Notebook",
    description: "A high-quality notebook for jotting down thoughts and ideas.",
    price: 15,
    tag: "stationery",
  },
  {
    id: 4,
    name: "Spa Gift Set",
    description:
      "A collection of bath and body products for a luxurious spa experience.",
    price: 30,
    tag: "beauty",
  },
  {
    id: 5,
    name: "Scented Soap",
    description: "A bar of handmade soap with a delightful scent.",
    price: 8,
    tag: "beauty",
  },
  {
    id: 6,
    name: "Pocket Watch",
    description: "A classic pocket watch with an elegant design.",
    price: 50,
    tag: "accessories",
  },
  {
    id: 7,
    name: "Cookbook",
    description: "A cookbook featuring a variety of delicious recipes.",
    price: 25,
    tag: "books",
  },
  {
    id: 8,
    name: "Gourmet Chocolate Box",
    description: "An assortment of gourmet chocolates from around the world.",
    price: 40,
    tag: "food",
  },
  {
    id: 9,
    name: "Scented Candle",
    description: "A single scented candle in a decorative jar.",
    price: 12,
    tag: "home_decor",
  },
  {
    id: 10,
    name: "Leather Wallet",
    description:
      "A genuine leather wallet with multiple card slots and a coin pocket.",
    price: 45,
    tag: "accessories",
  },
  {
    id: 11,
    name: "Potted Plant",
    description: "A small potted plant to add some greenery to any space.",
    price: 18,
    tag: "home_decor",
  },
  {
    id: 12,
    name: "Bluetooth Speaker",
    description: "A portable Bluetooth speaker for enjoying music on the go.",
    price: 60,
    tag: "electronics",
  },
  {
    id: 13,
    name: "Wine Bottle Opener Set",
    description:
      "A set including a wine bottle opener, stopper, and foil cutter.",
    price: 35,
    tag: "kitchen",
  },
  {
    id: 14,
    name: "Travel Mug",
    description: "An insulated travel mug to keep beverages hot or cold.",
    price: 20,
    tag: "kitchen",
  },
  {
    id: 15,
    name: "Art Print",
    description:
      "A framed art print featuring a beautiful painting or photograph.",
    price: 30,
    tag: "home_decor",
  },
  {
    id: 16,
    name: "Scented Diffuser",
    description: "A scented diffuser to fill the air with a pleasant aroma.",
    price: 25,
    tag: "home_decor",
  },
  {
    id: 17,
    name: "Cooking Utensil Set",
    description: "A set of essential cooking utensils for the kitchen.",
    price: 40,
    tag: "kitchen",
  },
  {
    id: 18,
    name: "Fitness Tracker",
    description:
      "A wearable fitness tracker to monitor daily activity and workouts.",
    price: 80,
    tag: "electronics",
  },
  {
    id: 19,
    name: "Tea Sampler",
    description: "A collection of different tea flavors for tea enthusiasts.",
    price: 15,
    tag: "food",
  },
  {
    id: 20,
    name: "Sunglasses",
    description:
      "A stylish pair of sunglasses to protect the eyes from the sun.",
    price: 35,
    tag: "accessories",
  },
  {
    id: 21,
    name: "Gourmet Cheese Selection",
    description: "A selection of gourmet cheeses from different regions.",
    price: 30,
    tag: "food",
  },
  {
    id: 22,
    name: "Journal Set",
    description: "A set of beautiful journals for writing and reflection.",
    price: 25,
    tag: "stationery",
  },
  {
    id: 23,
    name: "Plant-Based Cookbook",
    description: "A cookbook featuring delicious plant-based recipes.",
    price: 20,
    tag: "books",
  },
  {
    id: 24,
    name: "Essential Oil Set",
    description: "A set of essential oils for aromatherapy and relaxation.",
    price: 30,
    tag: "beauty",
  },
  {
    id: 25,
    name: "Portable Power Bank",
    description: "A portable power bank to charge devices on the go.",
    price: 50,
    tag: "electronics",
  },
  {
    id: 26,
    name: "Coffee Beans Sampler",
    description: "A sampler pack of different coffee bean varieties.",
    price: 15,
    tag: "food",
  },
  {
    id: 27,
    name: "Wireless Earbuds",
    description:
      "A pair of wireless earbuds for listening to music or taking calls.",
    price: 70,
    tag: "electronics",
  },
  {
    id: 28,
    name: "Scented Bath Bombs",
    description: "A set of scented bath bombs for a relaxing bath experience.",
    price: 20,
    tag: "beauty",
  },
  {
    id: 29,
    name: "Pocket Knife",
    description: "A versatile pocket knife with multiple tools.",
    price: 25,
    tag: "tools",
  },
  {
    id: 30,
    name: "Yoga Mat",
    description: "A high-quality yoga mat for practicing yoga or meditation.",
    price: 30,
    tag: "fitness",
  },
  {
    id: 31,
    name: "Gourmet Chocolate Truffles",
    description: "A box of decadent gourmet chocolate truffles.",
    price: 25,
    tag: "food",
  },
  {
    id: 32,
    name: "Smartphone Stand",
    description: "A portable smartphone stand for hands-free viewing.",
    price: 15,
    tag: "electronics",
  },
  {
    id: 33,
    name: "Cooking Spice Set",
    description: "A collection of premium cooking spices and herbs.",
    price: 20,
    tag: "kitchen",
  },
  {
    id: 34,
    name: "Scented Hand Lotion",
    description: "A moisturizing hand lotion with a pleasant scent.",
    price: 12,
    tag: "beauty",
  },
  {
    id: 35,
    name: "Travel Pillow",
    description: "A comfortable travel pillow for restful journeys.",
    price: 18,
    tag: "travel",
  },
  {
    id: 36,
    name: "Wireless Bluetooth Headphones",
    description:
      "A pair of wireless headphones for immersive audio experience.",
    price: 90,
    tag: "electronics",
  },
  {
    id: 37,
    name: "Gourmet Tea Infuser",
    description: "A stainless steel tea infuser for brewing loose-leaf tea.",
    price: 15,
    tag: "kitchen",
  },
  {
    id: 38,
    name: "Adult Coloring Book",
    description: "A coloring book with intricate designs for relaxation.",
    price: 12,
    tag: "books",
  },
  {
    id: 39,
    name: "Yoga Block",
    description:
      "A yoga block for providing support and stability in yoga poses.",
    price: 10,
    tag: "fitness",
  },
  {
    id: 40,
    name: "Gourmet Olive Oil Set",
    description:
      "A set of premium gourmet olive oils for culinary exploration.",
    price: 30,
    tag: "food",
  },
  {
    id: 41,
    name: "Polaroid Camera",
    description: "A vintage-style Polaroid camera for instant photo printing.",
    price: 80,
    tag: "electronics",
  },
  {
    id: 42,
    name: "Indoor Herb Garden Kit",
    description:
      "A kit for growing herbs indoors and adding freshness to meals.",
    price: 25,
    tag: "home_decor",
  },
  {
    id: 43,
    name: "Stainless Steel Water Bottle",
    description: "A durable and eco-friendly stainless steel water bottle.",
    price: 20,
    tag: "kitchen",
  },
  {
    id: 44,
    name: "Face Mask Variety Pack",
    description: "A pack of assorted face masks for different skin needs.",
    price: 15,
    tag: "beauty",
  },
  {
    id: 45,
    name: "Gourmet Popcorn Set",
    description: "A set of gourmet popcorn flavors for movie nights.",
    price: 18,
    tag: "food",
  },
  {
    id: 46,
    name: "Leather Journal",
    description: "A handcrafted leather journal for writing or sketching.",
    price: 35,
    tag: "stationery",
  },
  {
    id: 47,
    name: "Fitness Resistance Bands Set",
    description: "A set of resistance bands for versatile workouts.",
    price: 25,
    tag: "fitness",
  },
  {
    id: 48,
    name: "Bluetooth Shower Speaker",
    description: "A waterproof speaker for listening to music in the shower.",
    price: 30,
    tag: "electronics",
  },
  {
    id: 49,
    name: "Gourmet Hot Sauce Set",
    description: "A set of artisanal hot sauces for adding a kick to dishes.",
    price: 20,
    tag: "food",
  },
  {
    id: 50,
    name: "Aromatherapy Essential Oil Diffuser",
    description:
      "An essential oil diffuser with soothing color-changing lights.",
    price: 40,
    tag: "home_decor",
  },
];
