name: Check PR Status

on:
  pull_request:
    branches:
      - master

jobs:
  check_pr_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Compare PR branch with master
        id: check_branch
        run: |
          PR_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git checkout -B master origin/master
          git merge-base --is-ancestor origin/master "$PR_BRANCH"
          echo ::set-output name=is_behind_master::$?

      - name: Fail if PR is not up to date with master
        id: fail_check
        if: steps.check_branch.outputs.is_behind_master != '0'
        run: exit 1

  final_check:
    needs: check_pr_status
    runs-on: ubuntu-latest

    steps:
      - name: Check if previous step failed
        id: check_failure
        run: echo "Previous step failed"

      - name: Fail if PR is not up to date with master
        if: needs.check_pr_status.result != 'success' || needs.check_pr_status.outputs.fail_check == 'failure'
        run: exit 1
