name: Check PR Status

on:
  pull_request:
    branches:
      - master

jobs:
  check_pr_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Compare PR branch with master
        id: check_branch
        run: |
          echo "PR branch name: ${{ github.head_ref }}"
          echo "Branch ${{ github.head_ref }} is $(git rev-list --count origin/${{ github.head_ref }}..origin/master) commit(s) behind the master"

      - name: Check if PR branch is behind master
        run: |
          if [[ $(git rev-list --count origin/${{ github.head_ref }}..origin/master) -gt 0 ]]; then
            echo 10
          fi
          echo 1
