name: Update Check

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  update-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is updated to the master branch
      run: |
        git fetch origin master
        git diff --name-only origin/master...HEAD > changes.txt
        if [ -s changes.txt ]; then
          echo "::error file=changes.txt::This PR is not updated to the master branch. Please pull from master branch before making a PR."
          exit 1
        else
          echo "This PR is updated to the master branch."
        fi
